// Code generated by "stringer -type=Action"; DO NOT EDIT

package handlers

import "fmt"

const _Action_name = "CloseToNewPlayersStartIncrementReset"

var _Action_index = [...]uint8{0, 17, 22, 31, 36}

func (i Action) String() string {
	if i < 0 || i >= Action(len(_Action_index)-1) {
		return fmt.Sprintf("Action(%d)", i)
	}
	return _Action_name[_Action_index[i]:_Action_index[i+1]]
}
