// Code generated by "stringer -type=Role"; DO NOT EDIT

package retroengine

import "fmt"

const _Role_name = "AdminNormal"

var _Role_index = [...]uint8{0, 5, 11}

func (i Role) String() string {
	if i < 0 || i >= Role(len(_Role_index)-1) {
		return fmt.Sprintf("Role(%d)", i)
	}
	return _Role_name[_Role_index[i]:_Role_index[i+1]]
}
